name: Compile and Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: rosicley/workshop-productivity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cmake . -B build && cmake --build build
          ctest --test-dir build --output-on-failure
